name: Create - API Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Prisma generate
        run: |
          cp packages/create/.env.sample packages/create/.env
          sed -i 's/localhost/127.0.0.1/g' packages/create/.env
          cd packages/create
          npx prisma generate
          npx prisma db push

      - name: Run create api tests
        run: |
          npm run -w @webdevcody/create-launchpad dev &
          sleep 5
          npm run -w @webdevcody/create-launchpad test
